name: swift-android-native ci
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '45 2,13 * * *'
jobs:
  ci:
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-15-intel', 'ubuntu-latest']
        swift: ['6.2.3', 'nightly-6.3', 'nightly-main']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: "Build Swift Package for Android (Skip)"
        # Use a source build of skipstone until we have a release that includes
        # https://github.com/skiptools/skipstone/pull/199
        if: false
        run: |
          brew install skiptools/skip/skip || (brew update && brew install skiptools/skip/skip)

      - name: Checkout skipstone
        uses: actions/checkout@v6
        with:
          repository: skiptools/skipstone
          path: skipstone
          ref: main
          submodules: true
      - name: Build skipstone
        working-directory: skipstone
        run: |
          swift build --product SkipRunner
          # add skip local runner to path
          echo "${PWD}/scripts" >> $GITHUB_PATH

      - name: "Install swiftly"
        run: |
          brew install swiftly
          swiftly init --skip-install --assume-yes --quiet-shell-followup

      - name: "Install Swift SDK for Android"
        run: |
          skip android sdk install --verbose --version ${{ matrix.swift }}
          # https://github.com/swiftlang/swift-driver/pull/1879
          echo "ANDROID_NDK_ROOT=" >> $GITHUB_ENV

      - name: "Build package for Android"
        run: skip android build --build-tests

      - name: "Test Swift Package on Android (Skip)"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          script: skip android test --apk --verbose
      - name: "Test Swift Package on host OS"
        run: swift test
      - name: "Test Swift Package on iOS"
        #if: runner.os == 'macOS'
        if: false
        run: xcodebuild test -sdk "iphonesimulator" -destination "platform=iOS Simulator,name=iPhone 17" -scheme swift-android-native-Package

